#!/usr/bin/env python3
"""High-power CRN stochastic validation for Stochastic.

This script evaluates the full nonlinear six-node Stuart--Landau network with
20,000 common-random-number paths, explicitly includes the analytical modal cap
optimum, uses a dense local cap grid, forms paired and family-wise confidence
intervals, estimates a fixed-design quadratic vertex, and performs a nested
Euler--Maruyama step-halving check.

The calculation is resumable.  Use ``--reset`` once, then invoke repeatedly
with ``--chunk-paths`` until the final summary is produced.  Brownian increments
are generated by a fixed NumPy PCG64 stream and are shared across all caps.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
from pathlib import Path
from typing import Any

import numpy as np
from numba import get_num_threads, njit, prange, set_num_threads
from numpy.typing import NDArray
from scipy.stats import t as student_t

from network_experiments import (
    K0,
    LAM_RING,
    N,
    OMEGA,
    T,
    V_RING,
    modal_terminal_mse,
)

from artifact_paths import work_dir, output_dir, code_dir
ROOT = work_dir()
STATE_DIR = output_dir() / "checkpoint"
CHECKPOINT = STATE_DIR / "checkpoint.json"
PRIMARY_FILE = STATE_DIR / "primary.npy"
REFINE_FINE_FILE = STATE_DIR / "refine_dt_5e4.npy"
REFINE_COARSE_FILE = STATE_DIR / "refine_dt_1e3.npy"

SIGMA = 2.0e-3
PATHS = 20_000
REFINEMENT_PATHS = 10_000
PRIMARY_DT = 5.0e-4
COARSE_DT = 1.0e-3
BATCH_SIZE = 200
SEED = 20260829
ALPHA_CI = 0.05

CAP_RATIOS = np.array(
    [
        0.60,
        0.75,
        0.85,
        0.90,
        0.95,
        0.975,
        0.990,
        0.995,
        1.000,
        1.005,
        1.010,
        1.025,
        1.050,
        1.100,
        1.250,
        1.500,
    ],
    dtype=float,
)
QUADRATIC_RATIOS = np.array(
    [0.975, 0.99, 0.995, 1.0, 1.005, 1.01, 1.025],
    dtype=float,
)
REFINEMENT_RATIOS = np.array([0.95, 1.0, 1.05], dtype=float)


def phase_offsets() -> NDArray[np.float64]:
    values = 2.0 * np.array([0.08, -0.05, 0.12, -0.10, 0.03, -0.08])
    values -= values.mean()
    return values


def initial_network_state() -> NDArray[np.float64]:
    offsets = phase_offsets()
    return np.column_stack((np.cos(offsets), np.sin(offsets))).astype(float)


def locked_kopt() -> float:
    summary = json.loads((ROOT / "numerical_summary.json").read_text())
    return float(summary["Kopt_network_modal"])


def gain_matrix(caps: NDArray[np.float64], dt: float) -> NDArray[np.float64]:
    steps = int(round(T / dt))
    dt = T / steps
    times = np.arange(steps, dtype=float) * dt
    return np.minimum(caps[:, None], 1.0 / (T - times)[None, :])


@njit(cache=True, parallel=True, fastmath=False)
def _simulate_terminal_sq_batch(
    gains: NDArray[np.float64],
    brownian_increments: NDArray[np.float64],
    x0: NDArray[np.float64],
    dt: float,
    sigma: float,
) -> NDArray[np.float64]:
    steps, paths, n_nodes = brownian_increments.shape
    n_caps = gains.shape[0]
    output = np.empty((paths, n_caps), dtype=np.float64)

    for path in prange(paths):
        x = np.empty((n_caps, n_nodes, 2), dtype=np.float64)
        x_next = np.empty((n_caps, n_nodes, 2), dtype=np.float64)
        lap_dw = np.empty(n_nodes, dtype=np.float64)
        for c in range(n_caps):
            for i in range(n_nodes):
                x[c, i, 0] = x0[i, 0]
                x[c, i, 1] = x0[i, 1]

        for step in range(steps):
            time = step * dt
            tangent_x = -math.sin(OMEGA * time)
            tangent_y = math.cos(OMEGA * time)
            for i in range(n_nodes):
                lap_dw[i] = (
                    2.0 * brownian_increments[step, path, i]
                    - brownian_increments[step, path, (i - 1) % n_nodes]
                    - brownian_increments[step, path, (i + 1) % n_nodes]
                )

            for c in range(n_caps):
                scheduled_gain = K0 * gains[c, step]
                for i in range(n_nodes):
                    previous = (i - 1) % n_nodes
                    following = (i + 1) % n_nodes
                    xx = x[c, i, 0]
                    yy = x[c, i, 1]
                    radius_sq = xx * xx + yy * yy
                    coupling_x = 2.0 * xx - x[c, previous, 0] - x[c, following, 0]
                    coupling_y = 2.0 * yy - x[c, previous, 1] - x[c, following, 1]
                    field_x = xx - OMEGA * yy - radius_sq * xx
                    field_y = yy + OMEGA * xx - radius_sq * yy
                    noise_scalar = -scheduled_gain * sigma * lap_dw[i]
                    x_next[c, i, 0] = (
                        xx
                        + (field_x - scheduled_gain * coupling_x) * dt
                        + noise_scalar * tangent_x
                    )
                    x_next[c, i, 1] = (
                        yy
                        + (field_y - scheduled_gain * coupling_y) * dt
                        + noise_scalar * tangent_y
                    )
            temporary = x
            x = x_next
            x_next = temporary

        for c in range(n_caps):
            mean_x = 0.0
            mean_y = 0.0
            for i in range(n_nodes):
                mean_x += x[c, i, 0]
                mean_y += x[c, i, 1]
            mean_x /= n_nodes
            mean_y /= n_nodes
            disagreement_sq = 0.0
            for i in range(n_nodes):
                dx = x[c, i, 0] - mean_x
                dy = x[c, i, 1] - mean_y
                disagreement_sq += dx * dx + dy * dy
            output[path, c] = disagreement_sq
    return output


def find_index(values: NDArray[np.float64], target: float) -> int:
    index = int(np.argmin(np.abs(values - target)))
    if abs(float(values[index]) - target) > 1.0e-10 * max(1.0, abs(target)):
        raise ValueError(f"Target {target} not found")
    return index


def jsonable_rng_state(state: dict[str, Any]) -> dict[str, Any]:
    def convert(value: Any) -> Any:
        if isinstance(value, dict):
            return {key: convert(item) for key, item in value.items()}
        if isinstance(value, np.ndarray):
            return value.tolist()
        if isinstance(value, np.integer):
            return int(value)
        return value
    return convert(state)


def create_state(k_opt: float, caps: NDArray[np.float64]) -> dict[str, Any]:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    np.lib.format.open_memmap(PRIMARY_FILE, mode="w+", dtype="float64", shape=(PATHS, caps.size))
    np.lib.format.open_memmap(
        REFINE_FINE_FILE, mode="w+", dtype="float64", shape=(REFINEMENT_PATHS, REFINEMENT_RATIOS.size)
    )
    np.lib.format.open_memmap(
        REFINE_COARSE_FILE, mode="w+", dtype="float64", shape=(REFINEMENT_PATHS, REFINEMENT_RATIOS.size)
    )
    rng = np.random.default_rng(SEED)
    state = {
        "cursor": 0,
        "k_opt": k_opt,
        "caps": caps.tolist(),
        "rng_state": jsonable_rng_state(rng.bit_generator.state),
    }
    CHECKPOINT.write_text(json.dumps(state, indent=2) + "\n")
    return state


def load_rng(state: dict[str, Any]) -> np.random.Generator:
    rng = np.random.default_rng()
    rng.bit_generator.state = state["rng_state"]
    return rng


def t_interval(mean: float, se: float, df: int, alpha: float = ALPHA_CI) -> tuple[float, float]:
    critical = float(student_t.ppf(1.0 - alpha / 2.0, df))
    return mean - critical * se, mean + critical * se


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def quadratic_localization(
    outcomes: NDArray[np.float64], caps: NDArray[np.float64], k_opt: float
) -> dict[str, Any]:
    indices = [find_index(caps, k_opt * ratio) for ratio in QUADRATIC_RATIOS]
    x = caps[indices] / k_opt - 1.0
    design = np.column_stack((np.ones_like(x), x, x * x))
    map_matrix = np.linalg.solve(design.T @ design, design.T)
    path_coefficients = outcomes[:, indices] @ map_matrix.T
    coefficients = path_coefficients.mean(axis=0)
    covariance_mean = np.cov(path_coefficients, rowvar=False, ddof=1) / outcomes.shape[0]
    intercept, linear, quadratic = [float(value) for value in coefficients]
    if quadratic <= 0.0:
        raise RuntimeError("Local quadratic fit is not convex")
    ratio_shift = -linear / (2.0 * quadratic)
    estimated_cap = k_opt * (1.0 + ratio_shift)
    gradient = np.array(
        [0.0, -k_opt / (2.0 * quadratic), k_opt * linear / (2.0 * quadratic * quadratic)]
    )
    standard_error = math.sqrt(max(float(gradient @ covariance_mean @ gradient), 0.0))
    low, high = t_interval(estimated_cap, standard_error, outcomes.shape[0] - 1)
    fitted = design @ coefficients
    observed = outcomes[:, indices].mean(axis=0)
    residual = observed - fitted
    centered = observed - observed.mean()
    r_squared = 1.0 - float(residual @ residual) / float(centered @ centered)
    return {
        "ratios": QUADRATIC_RATIOS.tolist(),
        "coefficients_scaled_ratio_coordinate": coefficients.tolist(),
        "estimated_cap": estimated_cap,
        "standard_error": standard_error,
        "ci95_low": low,
        "ci95_high": high,
        "ratio_to_analytical_optimum": estimated_cap / k_opt,
        "r_squared": r_squared,
        "max_relative_fit_residual": float(np.max(np.abs(residual)) / np.mean(observed)),
    }


def finalize(k_opt: float, caps: NDArray[np.float64]) -> None:
    primary = np.load(PRIMARY_FILE, mmap_mode="r")
    refine_fine = np.load(REFINE_FINE_FILE, mmap_mode="r")
    refine_coarse = np.load(REFINE_COARSE_FILE, mmap_mode="r")
    reference_index = find_index(caps, k_opt)
    refinement_indices = [find_index(caps, k_opt * ratio) for ratio in REFINEMENT_RATIOS]
    modal_initial = V_RING.T @ phase_offsets()

    n = PATHS
    df = n - 1
    means = np.asarray(primary.mean(axis=0))
    standard_deviations = np.asarray(primary.std(axis=0, ddof=1))
    standard_errors = standard_deviations / math.sqrt(n)
    t_critical = float(student_t.ppf(1.0 - ALPHA_CI / 2.0, df))
    ci_low = means - t_critical * standard_errors
    ci_high = means + t_critical * standard_errors

    reference = np.asarray(primary[:, reference_index])
    differences = np.asarray(primary) - reference[:, None]
    difference_means = differences.mean(axis=0)
    difference_standard_errors = differences.std(axis=0, ddof=1) / math.sqrt(n)
    paired_ci_low = difference_means - t_critical * difference_standard_errors
    paired_ci_high = difference_means + t_critical * difference_standard_errors
    simultaneous_critical = float(
        student_t.ppf(1.0 - ALPHA_CI / (2.0 * (caps.size - 1)), df)
    )
    simultaneous_low = difference_means - simultaneous_critical * difference_standard_errors
    simultaneous_high = difference_means + simultaneous_critical * difference_standard_errors

    exact_modal = np.array(
        [modal_terminal_mse(float(cap), SIGMA, LAM_RING, modal_initial) for cap in caps]
    )
    relative_modal_error = (means - exact_modal) / exact_modal
    correlations = np.ones(caps.size)
    variance_reduction = np.full(caps.size, np.inf)
    reference_variance = float(np.var(reference, ddof=1))
    for index in range(caps.size):
        if index == reference_index:
            continue
        correlations[index] = float(np.corrcoef(np.asarray(primary[:, index]), reference)[0, 1])
        independent_variance = float(np.var(primary[:, index], ddof=1)) + reference_variance
        paired_variance = float(np.var(differences[:, index], ddof=1))
        variance_reduction[index] = independent_variance / paired_variance

    cap_rows: list[dict[str, Any]] = []
    for index, cap in enumerate(caps):
        cap_rows.append(
            {
                "K": float(cap),
                "K_over_Kopt": float(cap / k_opt),
                "modal_exact_mse": float(exact_modal[index]),
                "nonlinear_mc_mse": float(means[index]),
                "mc_se": float(standard_errors[index]),
                "mc_ci95_low": float(ci_low[index]),
                "mc_ci95_high": float(ci_high[index]),
                "relative_modal_error": float(relative_modal_error[index]),
                "paired_difference_vs_Kopt": float(difference_means[index]),
                "paired_se": float(difference_standard_errors[index]),
                "paired_ci95_low": float(paired_ci_low[index]),
                "paired_ci95_high": float(paired_ci_high[index]),
                "paired_simultaneous_ci95_low": float(simultaneous_low[index]),
                "paired_simultaneous_ci95_high": float(simultaneous_high[index]),
                "correlation_with_Kopt": float(correlations[index]),
                "crn_variance_reduction_factor": (
                    "inf" if not math.isfinite(float(variance_reduction[index])) else float(variance_reduction[index])
                ),
                "significantly_worse_individual_95": bool(paired_ci_low[index] > 0.0),
                "significantly_worse_simultaneous_95": bool(simultaneous_low[index] > 0.0),
                "significantly_better_simultaneous_95": bool(simultaneous_high[index] < 0.0),
            }
        )
    write_csv(ROOT / "stochastic_crn_cap_validation.csv", list(cap_rows[0].keys()), cap_rows)

    unresolved = np.where(simultaneous_low <= 0.0)[0]
    unresolved_ratios = caps[unresolved] / k_opt
    localization_low = float(np.min(unresolved_ratios))
    localization_high = float(np.max(unresolved_ratios))
    empirical_index = int(np.argmin(means))
    quadratic = quadratic_localization(np.asarray(primary), caps, k_opt)

    refinement_rows: list[dict[str, Any]] = []
    max_relative_shift = 0.0
    for local_index, cap_index in enumerate(refinement_indices):
        coarse_values = np.asarray(refine_coarse[:, local_index])
        fine_values = np.asarray(refine_fine[:, local_index])
        coarse_mean = float(coarse_values.mean())
        fine_mean = float(fine_values.mean())
        paired = coarse_values - fine_values
        paired_mean = float(paired.mean())
        paired_se = float(paired.std(ddof=1) / math.sqrt(REFINEMENT_PATHS))
        low, high = t_interval(paired_mean, paired_se, REFINEMENT_PATHS - 1)
        relative_shift = paired_mean / fine_mean
        max_relative_shift = max(max_relative_shift, abs(relative_shift))
        refinement_rows.append(
            {
                "K": float(caps[cap_index]),
                "K_over_Kopt": float(caps[cap_index] / k_opt),
                "mean_dt_1e-3": coarse_mean,
                "mean_dt_5e-4": fine_mean,
                "paired_dt_1e-3_minus_5e-4": paired_mean,
                "paired_se": paired_se,
                "paired_ci95_low": low,
                "paired_ci95_high": high,
                "relative_shift": relative_shift,
            }
        )
    write_csv(ROOT / "stochastic_step_refinement.csv", list(refinement_rows[0].keys()), refinement_rows)

    np.savez_compressed(
        ROOT / "stochastic_crn_pathwise_terminal_mse.npz",
        caps=caps,
        Kopt=np.array([k_opt]),
        terminal_squared_disagreement=np.asarray(primary),
        refinement_caps=caps[refinement_indices],
        refinement_dt_1e3=np.asarray(refine_coarse),
        refinement_dt_5e4=np.asarray(refine_fine),
        seed=np.array([SEED], dtype=np.int64),
    )

    local_mask = (caps / k_opt >= 0.95) & (caps / k_opt <= 1.05)
    finite_local_vrf = variance_reduction[local_mask & np.isfinite(variance_reduction)]
    empirical_ordering_stable = bool(
        refinement_rows[0]["mean_dt_1e-3"] > refinement_rows[1]["mean_dt_1e-3"]
        and refinement_rows[2]["mean_dt_1e-3"] > refinement_rows[1]["mean_dt_1e-3"]
        and refinement_rows[0]["mean_dt_5e-4"] > refinement_rows[1]["mean_dt_5e-4"]
        and refinement_rows[2]["mean_dt_5e-4"] > refinement_rows[1]["mean_dt_5e-4"]
    )

    summary: dict[str, Any] = {
        "experiment": "Stochastic",
        "paths": PATHS,
        "refinement_paths": REFINEMENT_PATHS,
        "seed": SEED,
        "sigma": SIGMA,
        "primary_dt": PRIMARY_DT,
        "coarse_dt": COARSE_DT,
        "numba_threads": get_num_threads(),
        "Kopt_modal": k_opt,
        "Kopt_modal_mse": float(exact_modal[reference_index]),
        "Kopt_nonlinear_mc_mse": float(means[reference_index]),
        "Kopt_marginal_se": float(standard_errors[reference_index]),
        "Kopt_marginal_relative_se": float(standard_errors[reference_index] / means[reference_index]),
        "Kopt_nonlinear_modal_relative_error": float(relative_modal_error[reference_index]),
        "cap_count": int(caps.size),
        "cap_ratios": CAP_RATIOS.tolist(),
        "cap_grid": caps.tolist(),
        "empirical_grid_minimum_cap": float(caps[empirical_index]),
        "empirical_grid_minimum_ratio": float(caps[empirical_index] / k_opt),
        "empirical_grid_minimum_mse": float(means[empirical_index]),
        "simultaneous_ci_critical": simultaneous_critical,
        "simultaneous_unresolved_ratio_interval": [localization_low, localization_high],
        "simultaneous_unresolved_cap_interval": [localization_low * k_opt, localization_high * k_opt],
        "no_tested_cap_significantly_better_than_Kopt": bool(np.all(simultaneous_high >= 0.0)),
        "minimum_local_correlation_with_Kopt": float(np.min(correlations[local_mask])),
        "minimum_local_crn_variance_reduction": float(np.min(finite_local_vrf)),
        "maximum_absolute_nonlinear_modal_relative_error": float(np.max(np.abs(relative_modal_error))),
        "quadratic_localization": quadratic,
        "step_refinement": {
            "paths": REFINEMENT_PATHS,
            "ratios": REFINEMENT_RATIOS.tolist(),
            "maximum_relative_shift": max_relative_shift,
            "empirical_ordering_stable": empirical_ordering_stable,
        },
    }

    checks: list[dict[str, Any]] = []
    def check(name: str, passed: bool, detail: Any) -> None:
        checks.append({"name": name, "passed": bool(passed), "detail": detail})

    check("path count", PATHS >= 20_000, PATHS)
    check("refinement path count", REFINEMENT_PATHS >= 10_000, REFINEMENT_PATHS)
    check("analytical optimum included exactly", caps[reference_index] == k_opt, caps[reference_index])
    check("primary step halves legacy step", PRIMARY_DT == 0.5 * COARSE_DT, [PRIMARY_DT, COARSE_DT])
    check("all terminal statistics finite", bool(np.all(np.isfinite(primary))), float(np.max(primary)))
    check("all terminal statistics nonnegative", bool(np.all(primary >= 0.0)), float(np.min(primary)))
    check(
        "marginal relative standard error at optimum below 0.5 percent",
        standard_errors[reference_index] / means[reference_index] < 5.0e-3,
        standard_errors[reference_index] / means[reference_index],
    )
    check(
        "local cap correlations exceed 0.99",
        float(np.min(correlations[local_mask])) > 0.99,
        float(np.min(correlations[local_mask])),
    )
    check(
        "local CRN variance reduction exceeds 100",
        float(np.min(finite_local_vrf)) > 100.0,
        float(np.min(finite_local_vrf)),
    )
    check(
        "no tested cap simultaneously better than Kopt",
        bool(np.all(simultaneous_high >= 0.0)),
        float(np.min(simultaneous_high)),
    )
    check(
        "simultaneous localization contains Kopt",
        localization_low <= 1.0 <= localization_high,
        [localization_low, localization_high],
    )
    check(
        "simultaneous localization width at most three percent",
        localization_high - localization_low <= 0.03,
        localization_high - localization_low,
    )
    check(
        "quadratic confidence interval contains Kopt",
        quadratic["ci95_low"] <= k_opt <= quadratic["ci95_high"],
        [quadratic["ci95_low"], k_opt, quadratic["ci95_high"]],
    )
    check("quadratic fit R squared exceeds 0.999", quadratic["r_squared"] > 0.999, quadratic["r_squared"])
    check("step-halving relative shift below 0.2 percent", max_relative_shift < 2.0e-3, max_relative_shift)
    check("step-halving preserves local ordering", empirical_ordering_stable, refinement_rows)
    check(
        "nonlinear-modal discrepancy below ten percent",
        float(np.max(np.abs(relative_modal_error))) < 0.10,
        float(np.max(np.abs(relative_modal_error))),
    )
    for index, cap in enumerate(caps):
        check(f"cap {cap:.12g} exact modal MSE positive", exact_modal[index] > 0.0, exact_modal[index])
        if index != reference_index:
            check(
                f"cap {cap:.12g} paired standard error positive",
                difference_standard_errors[index] > 0.0,
                difference_standard_errors[index],
            )

    validation = {
        "status": "PASS" if all(item["passed"] for item in checks) else "FAIL",
        "checks_passed": sum(item["passed"] for item in checks),
        "checks_total": len(checks),
        "checks": checks,
    }
    summary["validation"] = {
        "status": validation["status"],
        "checks_passed": validation["checks_passed"],
        "checks_total": validation["checks_total"],
    }
    (ROOT / "stochastic_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    (ROOT / "stochastic_validation.json").write_text(json.dumps(validation, indent=2) + "\n")

    lines = [
        "Stochastic COMMON-RANDOM-NUMBER STOCHASTIC VALIDATION",
        "=" * 68,
        f"status: {validation['status']}",
        f"checks: {validation['checks_passed']}/{validation['checks_total']}",
        f"paths: {PATHS}",
        f"primary Euler--Maruyama step: {PRIMARY_DT:.8g}",
        f"analytical Kopt: {k_opt:.12f}",
        f"empirical grid minimum: {caps[empirical_index]:.12f}",
        f"endpoints of unresolved tested ratios: [{localization_low:.6f}, {localization_high:.6f}]",
        f"quadratic fitted vertex: {quadratic['estimated_cap']:.12f}",
        f"quadratic 95% CI: [{quadratic['ci95_low']:.12f}, {quadratic['ci95_high']:.12f}]",
        f"minimum local CRN correlation: {np.min(correlations[local_mask]):.12f}",
        f"minimum local variance-reduction factor: {np.min(finite_local_vrf):.6f}",
        f"Kopt nonlinear/modal relative error: {relative_modal_error[reference_index]:.6%}",
        f"max nonlinear/modal relative error: {np.max(np.abs(relative_modal_error)):.6%}",
        f"max step-halving relative shift: {max_relative_shift:.6%}",
        "",
    ]
    for item in checks:
        lines.append(f"[{'PASS' if item['passed'] else 'FAIL'}] {item['name']}: {item['detail']}")
    (ROOT / "stochastic_validation.txt").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:17]))
    if validation["status"] != "PASS":
        raise SystemExit("Stochastic stochastic validation failed")


def process_chunk(chunk_paths: int, reset: bool) -> None:
    k_opt = locked_kopt()
    caps = k_opt * CAP_RATIOS
    if reset and STATE_DIR.exists():
        import shutil
        shutil.rmtree(STATE_DIR)
    if not CHECKPOINT.exists():
        state = create_state(k_opt, caps)
    else:
        state = json.loads(CHECKPOINT.read_text())
    if abs(float(state["k_opt"]) - k_opt) > 1.0e-14 or not np.allclose(np.asarray(state["caps"]), caps):
        raise RuntimeError("Checkpoint design does not match active Stochastic design")

    cursor = int(state["cursor"])
    if cursor >= PATHS:
        finalize(k_opt, caps)
        return

    threads = int(os.environ.get("NUMBA_NUM_THREADS", min(4, get_num_threads())))
    set_num_threads(max(1, min(threads, get_num_threads())))
    rng = load_rng(state)
    primary = np.load(PRIMARY_FILE, mmap_mode="r+")
    refine_fine = np.load(REFINE_FINE_FILE, mmap_mode="r+")
    refine_coarse = np.load(REFINE_COARSE_FILE, mmap_mode="r+")
    primary_gains = gain_matrix(caps, PRIMARY_DT)
    refine_caps = k_opt * REFINEMENT_RATIOS
    refinement_indices = [find_index(caps, value) for value in refine_caps]
    coarse_gains = gain_matrix(refine_caps, COARSE_DT)
    x0 = initial_network_state()
    primary_steps = int(round(T / PRIMARY_DT))
    coarse_steps = int(round(T / COARSE_DT))
    target = min(PATHS, cursor + chunk_paths)
    sqrt_dt = math.sqrt(PRIMARY_DT)

    while cursor < target:
        batch = min(BATCH_SIZE, target - cursor)
        fine_dw = rng.standard_normal((primary_steps, batch, N)) * sqrt_dt
        primary_batch = _simulate_terminal_sq_batch(primary_gains, fine_dw, x0, PRIMARY_DT, SIGMA)
        primary[cursor : cursor + batch, :] = primary_batch
        if cursor < REFINEMENT_PATHS:
            refine_batch = min(batch, REFINEMENT_PATHS - cursor)
            refine_fine[cursor : cursor + refine_batch, :] = primary_batch[:refine_batch, refinement_indices]
            coarse_dw = fine_dw[:, :refine_batch, :].reshape(coarse_steps, 2, refine_batch, N).sum(axis=1)
            refine_coarse[cursor : cursor + refine_batch, :] = _simulate_terminal_sq_batch(
                coarse_gains, coarse_dw, x0, COARSE_DT, SIGMA
            )
        cursor += batch
        print(f"Stochastic CRN simulation: {cursor}/{PATHS} paths", flush=True)

    primary.flush()
    refine_fine.flush()
    refine_coarse.flush()
    state["cursor"] = cursor
    state["rng_state"] = jsonable_rng_state(rng.bit_generator.state)
    CHECKPOINT.write_text(json.dumps(state, indent=2) + "\n")
    if cursor >= PATHS:
        finalize(k_opt, caps)
    else:
        print(f"Checkpoint saved at {cursor}/{PATHS}; rerun to continue.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chunk-paths", type=int, default=PATHS)
    parser.add_argument("--reset", action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    if args.chunk_paths <= 0 or args.chunk_paths % BATCH_SIZE != 0:
        raise SystemExit(f"--chunk-paths must be a positive multiple of {BATCH_SIZE}")
    process_chunk(args.chunk_paths, args.reset)
